@startuml Component Diagram

skinparam component {
    backgroundColor<<presentation>> Lightblue
    backgroundColor<<container>> Lightgreen
}

package GroupsDetails.page {
    component "GroupDetailsPage"  as root <<container>>

    component "TwoCollumnLayout" as tcl <<container>>

    component "Header" as h <<presentation>>

    component "Group" as g1 <<container>>
    component "Button" as b1 <<presentation>>
    component "Button" as b2 <<presentation>>

    component "GroupFields" as gf <<presentation>>

    component "EditModal" as em <<presentation>>
    component "AddModal" as am <<presentation>>

    component "Fieldset" as f1 <<presentation>>
    component "TextInput" as ti1 <<presentation>>

    component "Fieldset" as f2 <<presentation>>

}

package ApiHelper {
    component "GroupApiHelper" as gapi <<container>>
}

root --> tcl

tcl --> h
tcl --> gf

tcl --> g1
g1 --> b1
g1 --> b2

gf --> em
gf --> am

gf ..> gapi: getAllGroups()
gf ..> gapi: deleteGroup()

@enduml