import type { SimpleUserT } from "@/types/Types.js";

export const userMockData: SimpleUserT[] = [
    {
        username: "alice.mueller",
        name: "Alice Müller",
        firstName: "Alice",
        lastName: "Müller",
        systemrole: "admin",
        email: "alice.mueller@example.com",
    },
    {
        username: "bob.schneider",
        name: "Bob Schneider",
        firstName: "Bob",
        lastName: "Schneider",
        systemrole: "member",
        email: "bob.schneider@example.com",
    },
    {
        username: "clara.fischer",
        name: "Clara Fischer",
        firstName: "Clara",
        lastName: "Fischer",
        systemrole: "member",
        email: "clara.fischer@example.com",
    },
    {
        username: "david.becker",
        name: "David Becker",
        firstName: "David",
        lastName: "Becker",
        systemrole: "member",
        email: "david.becker@example.com",
    },
    {
        username: "eva.wagner",
        name: "Eva Wagner",
        firstName: "Eva",
        lastName: "Wagner",
        systemrole: "admin",
        email: "eva.wagner@example.com",
    },
    {
        username: "felix.braun",
        name: "Felix Braun",
        firstName: "Felix",
        lastName: "Braun",
        systemrole: "member",
        email: "felix.braun@example.com",
    },
    {
        username: "greta.hofmann",
        name: "Greta Hofmann",
        firstName: "Greta",
        lastName: "Hofmann",
        systemrole: "member",
        email: "greta.hofmann@example.com",
    },
    {
        username: "henry.krause",
        name: "Henry Krause",
        firstName: "Henry",
        lastName: "Krause",
        systemrole: "member",
        email: "henry.krause@example.com",
    },
    {
        username: "isabel.koenig",
        name: "Isabel König",
        firstName: "Isabel",
        lastName: "König",
        systemrole: "member",
        email: "isabel.koenig@example.com",
    },
    {
        username: "jonas.vogel",
        name: "Jonas Vogel",
        firstName: "Jonas",
        lastName: "Vogel",
        systemrole: "member",
        email: "jonas.vogel@example.com",
    },
    {
        username: "klara.busch",
        name: "Klara Busch",
        firstName: "Klara",
        lastName: "Busch",
        systemrole: "admin",
        email: "klara.busch@example.com",
    },
    {
        username: "lukas.wolf",
        name: "Lukas Wolf",
        firstName: "Lukas",
        lastName: "Wolf",
        systemrole: "member",
        email: "lukas.wolf@example.com",
    },
    {
        username: "mara.weiss",
        name: "Mara Weiß",
        firstName: "Mara",
        lastName: "Weiß",
        systemrole: "member",
        email: "mara.weiss@example.com",
    },
    {
        username: "noah.schaefer",
        name: "Noah Schäfer",
        firstName: "Noah",
        lastName: "Schäfer",
        systemrole: "member",
        email: "noah.schaefer@example.com",
    },
    {
        username: "olivia.hartmann",
        name: "Olivia Hartmann",
        firstName: "Olivia",
        lastName: "Hartmann",
        systemrole: "member",
        email: "olivia.hartmann@example.com",
    },
    {
        username: "paul.neumann",
        name: "Paul Neumann",
        firstName: "Paul",
        lastName: "Neumann",
        systemrole: "admin",
        email: "paul.neumann@example.com",
    },
    {
        username: "quentin.richter",
        name: "Quentin Richter",
        firstName: "Quentin",
        lastName: "Richter",
        systemrole: "member",
        email: "quentin.richter@example.com",
    },
    {
        username: "rosa.lange",
        name: "Rosa Lange",
        firstName: "Rosa",
        lastName: "Lange",
        systemrole: "member",
        email: "rosa.lange@example.com",
    },
    {
        username: "stefan.keller",
        name: "Stefan Keller",
        firstName: "Stefan",
        lastName: "Keller",
        systemrole: "member",
        email: "stefan.keller@example.com",
    },
    {
        username: "tina.schmitt",
        name: "Tina Schmitt",
        firstName: "Tina",
        lastName: "Schmitt",
        systemrole: "member",
        email: "tina.schmitt@example.com",
    },
    {
        username: "max.mustermann",
        name: "Max Mustermann",
        firstName: "Max",
        lastName: "Mustermann",
        systemrole: "member",
        email: "max.mustermann@example.com",
    },
];
