import type { SimpleUserT } from "@/types/Types";

export const userMockData: SimpleUserT[] = [
  {
    username: "alice.mueller",
    name: "Alice Müller",
    firstName: "Alice",
    lastName: "Müller",
    systemrole: "System-Admin",
    email: "alice.mueller@example.com",
  },
  {
    username: "bob.schneider",
    name: "Bob Schneider",
    firstName: "Bob",
    lastName: "Schneider",
    systemrole: "System-Member",
    email: "bob.schneider@example.com",
  },
  {
    username: "clara.fischer",
    name: "Clara Fischer",
    firstName: "Clara",
    lastName: "Fischer",
    systemrole: "System-Member",
    email: "clara.fischer@example.com",
  },
  {
    username: "david.becker",
    name: "David Becker",
    firstName: "David",
    lastName: "Becker",
    systemrole: "System-Member",
    email: "david.becker@example.com",
  },
  {
    username: "eva.wagner",
    name: "Eva Wagner",
    firstName: "Eva",
    lastName: "Wagner",
    systemrole: "System-Admin",
    email: "eva.wagner@example.com",
  },
  {
    username: "felix.braun",
    name: "Felix Braun",
    firstName: "Felix",
    lastName: "Braun",
    systemrole: "System-Member",
    email: "felix.braun@example.com",
  },
  {
    username: "greta.hofmann",
    name: "Greta Hofmann",
    firstName: "Greta",
    lastName: "Hofmann",
    systemrole: "System-Member",
    email: "greta.hofmann@example.com",
  },
  {
    username: "henry.krause",
    name: "Henry Krause",
    firstName: "Henry",
    lastName: "Krause",
    systemrole: "System-Member",
    email: "henry.krause@example.com",
  },
  {
    username: "isabel.koenig",
    name: "Isabel König",
    firstName: "Isabel",
    lastName: "König",
    systemrole: "System-Member",
    email: "isabel.koenig@example.com",
  },
  {
    username: "jonas.vogel",
    name: "Jonas Vogel",
    firstName: "Jonas",
    lastName: "Vogel",
    systemrole: "System-Member",
    email: "jonas.vogel@example.com",
  },
  {
    username: "klara.busch",
    name: "Klara Busch",
    firstName: "Klara",
    lastName: "Busch",
    systemrole: "System-Admin",
    email: "klara.busch@example.com",
  },
  {
    username: "lukas.wolf",
    name: "Lukas Wolf",
    firstName: "Lukas",
    lastName: "Wolf",
    systemrole: "System-Member",
    email: "lukas.wolf@example.com",
  },
  {
    username: "mara.weiss",
    name: "Mara Weiß",
    firstName: "Mara",
    lastName: "Weiß",
    systemrole: "System-Member",
    email: "mara.weiss@example.com",
  },
  {
    username: "noah.schaefer",
    name: "Noah Schäfer",
    firstName: "Noah",
    lastName: "Schäfer",
    systemrole: "System-Member",
    email: "noah.schaefer@example.com",
  },
  {
    username: "olivia.hartmann",
    name: "Olivia Hartmann",
    firstName: "Olivia",
    lastName: "Hartmann",
    systemrole: "System-Member",
    email: "olivia.hartmann@example.com",
  },
  {
    username: "paul.neumann",
    name: "Paul Neumann",
    firstName: "Paul",
    lastName: "Neumann",
    systemrole: "System-Admin",
    email: "paul.neumann@example.com",
  },
  {
    username: "quentin.richter",
    name: "Quentin Richter",
    firstName: "Quentin",
    lastName: "Richter",
    systemrole: "System-Member",
    email: "quentin.richter@example.com",
  },
  {
    username: "rosa.lange",
    name: "Rosa Lange",
    firstName: "Rosa",
    lastName: "Lange",
    systemrole: "System-Member",
    email: "rosa.lange@example.com",
  },
  {
    username: "stefan.keller",
    name: "Stefan Keller",
    firstName: "Stefan",
    lastName: "Keller",
    systemrole: "System-Member",
    email: "stefan.keller@example.com",
  },
  {
    username: "tina.schmitt",
    name: "Tina Schmitt",
    firstName: "Tina",
    lastName: "Schmitt",
    systemrole: "System-Member",
    email: "tina.schmitt@example.com",
  },
];
